name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Start Database
        run: npm run test:services:start
        
      - run: npm install
      - run: npm test

      - run: npm run coverage

      - name: Code Coverage
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{ secrets.CODECOV_KEY }}