name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }}
    steps:

      # Use preinstalled PostgreSQL 
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Create Database
        run: |
          sudo -u postgres psql -c "create database keyv_test;" -U postgres

      - name: Set User Password
        run: |
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD ''; ALTER ROLE" -U postgres

      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        
      - run: npm install
      - run: npm test