services:
  keyv_postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: keyv_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - 5432:5432/tcp
  keyv_postgres_1:
    build:
      context: packages/postgres
      dockerfile: Dockerfile.ssl
    command: postgres -c 'max_connections=200' -c 'ssl=on' -c 'ssl_cert_file=/keyv_postgres_ssl/server.crt' -c 'ssl_key_file=/keyv_postgres_ssl/server.key' -c 'hba_file=/keyv_postgres_ssl/pg_hba.conf' -c "listen_addresses=*"
    environment:
      POSTGRES_DB: keyv_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - 5433:5432/tcp
  keyv_mysql:
    image: mysql/mysql-server:latest
    command: [ "mysqld",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--bind-address=0.0.0.0",
                "--default_authentication_plugin=mysql_native_password" ]
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: keyv_test
      MYSQL_USER: mysql
      MYSQL_ROOT_HOST: '%'
  keyv_mysql_1:
        image: "mysql/mysql-server:latest"
        command: [ "mysqld",
                    "--character-set-server=utf8mb4",
                    "--collation-server=utf8mb4_unicode_ci",
                    "--require_secure_transport=ON",
                    "--bind-address=0.0.0.0",
                    "--ssl-ca=/etc/certs/ca.pem",
                    "--ssl-cert=/etc/certs/server-cert.pem",
                    "--ssl-key=/etc/certs/server-key.pem",
                    "--default_authentication_plugin=mysql_native_password" ]
        ports:
          - "3307:3306"
        volumes:
          - type: bind
            source: ./packages/mysql/test/certs
            target: /etc/certs/
        restart: always
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: keyv_test
          MYSQL_ROOT_HOST: '%'
  keyv_redis:
    image: redis:latest
    environment:
      REDIS_HOST: redis
    ports:
      - 6379:6379
  keyv_redis_1:
    image: redis:latest
    command: redis-server --port 0 --tls-port 6380 --tls-cert-file /tls/redis.crt --tls-key-file /tls/redis.key --tls-ca-cert-file /tls/ca.crt --tls-auth-clients no
    environment:
      REDIS_HOST: redis
    ports:
      - 6380:6380
    volumes:
      - ./packages/redis/tls:/tls
  keyv_mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  keyv_memcached:
    image: memcached:latest
    ports:
        - "11211:11211"
  keyv_etcd:
    image: bitnami/etcd:latest
    platform: linux/arm64/v8
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
        - 2379:2379
        - 2380:2380

        
