language: node_js
node_js:
  - 10

cache: yarn

services:
  - memcached

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - yarn add codecov --global

script:
  - yarn test
  - yarn report-coverage
  - codecov