services:
  redis-1:
    image: redis:latest
    container_name: redis-cluster-1
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7001 --cluster-announce-bus-port 17001
    network_mode: host
    volumes:
      - redis-1-data:/data

  redis-2:
    image: redis:latest
    container_name: redis-cluster-2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7002 --cluster-announce-bus-port 17002
    network_mode: host
    volumes:
      - redis-2-data:/data

  redis-3:
    image: redis:latest
    container_name: redis-cluster-3
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7003 --cluster-announce-bus-port 17003
    network_mode: host
    volumes:
      - redis-3-data:/data

  redis-cluster-init:
    image: redis:latest
    container_name: redis-cluster-init
    network_mode: host
    depends_on:
      - redis-1
      - redis-2
      - redis-3
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "sleep 5 && \
      redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 --cluster-replicas 0 --cluster-yes && \
      echo 'Cluster created successfully' && \
      redis-cli -p 7001 cluster info"

volumes:
  redis-1-data:
  redis-2-data:
  redis-3-data: