language: node_js
node_js:
  - '8'
  - '6'
  - '4'
addons:
  postgresql: '9.5'
before_script:
  - psql -c 'create database keyv_test;' -U postgres
script: npm test
after_success: npm run coverage
notifications:
  email:
    on_success: never
