version: '2'
services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: keyv_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    stdin_open: true
    tty: true
    ports:
    - 5432:5432/tcp