language: node_js
node_js:
  - '8'
  - '6'
  - '4'
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE keyv_test;'
script: npm test
after_success: npm run coverage
notifications:
  email:
    on_success: never
