language: node_js
node_js:
  - '8'
  - '6'
  - '4'
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE keyv_test;'
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON keyv_test.* TO 'mysql'@'localhost';'
script: npm test
after_success: npm run coverage
notifications:
  email:
    on_success: never
