name: deno

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deno-test:
    runs-on: ubuntu-latest
    name: deno
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          cache: true

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Approve Builds
        run: pnpm approve-builds

      - name: Build Serialize
        run: pnpm build:keyv:serialize

      - name: Build Keyv
        run: pnpm build:keyv

      - name: Run Keyv Deno Smoke Tests
        working-directory: core/keyv
        run: deno test --import-map test/deno.import_map.json test/deno.test.ts
