name: deploy-website

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  setup-build-deploy:
    name: deploy-website
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        with:
          mode: firewall-free
          firewall-version: "1.15.0"

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Use Node.js 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install Dependencies
        run: sfw pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build

      - name: Build Website
        run: pnpm website:build

      - name: Install Wrangler
        run: sfw pnpm add -Dw wrangler@4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy website/dist --project-name=keyv --branch=main
