name: deploy-website

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  setup-build-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    # Test
    - name: Use Node.js 22
      uses: actions/setup-node@v7
      with:
        node-version: 22

    - name: Install pnpm
      uses: pnpm/action-setup@v6

    - name: Install Dependencies  
      run: pnpm install --frozen-lockfile

    - name: Install Dependencies  
      run: pnpm build
      
    - name: Build Website
      run: pnpm website:build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v4
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        command: pages deploy packages/website/dist --project-name=keyv --branch=main
