name: tests-compress-brotli

on:
  pull_request:
    branches: [ main ]
    paths: 
      - packages/compress-brotli/**

env:
  PACKAGE_NAME: '@keyv/compress-brotli'
  COVERAGE_FILE: ./packages/compress-brotli/coverage.lcov

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '18' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Start Services
        run: yarn test:services:start

      - name: Install Dependencies  
        run: yarn
        
      - name: Test Packages
        run: yarn workspace ${{ env.PACKAGE_NAME }} test

      - name: Generate Code Coverage Report
        run: yarn coverage

      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_KEY }}
          verbose: true
          files: ./packages/keyv/coverage.lcov,./packages/mysql/coverage.lcov,./packages/test-suite/coverage.lcov,./packages/sqlite/coverage.lcov,./packages/postgres/coverage.lcov,./packages/mongo/coverage.lcov,./packages/redis/coverage.lcov,./packages/memcache/coverage.lcov,./packages/etcd/coverage.lcov,./packages/offline/coverage.lcov,./packages/tiered/coverage.lcov
