name: tests-compress-brotli

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/compress-brotli/**'
      - '.github/workflows/tests-compress-brotli.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '18' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Start Services
        run: yarn test:services:start

      - name: Install Dependencies  
        run: yarn
        
      - name: Test Packages
        run: yarn workspace @keyv/compress-brotli run test:ci:coverage

      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_KEY }}
          verbose: true
          files: ./packages/compress-brotli/coverage/lcov.info