name: integrations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn

# memcached
    - name: Setup Memcached Service
      uses: niden/actions-memcached@v7

    - name: Testing Memcached Service  
      run: yarn test

# memcachier

    - name: Testing Memcachier Service  
      run: URI=${{ secrets.MEMCACHIER_URI }} yarn test

# redislabs

    - name: Testing RedisLabs Service 
      run: URI=${{ secrets.REDISLABS_URI }} yarn test